// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package grpc4ars is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	RequestContext
	ResponseContext
	HBRequest
	HBResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestContext struct {
	Session string `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Sevice  string `protobuf:"bytes,2,opt,name=sevice" json:"sevice,omitempty"`
	Input   string `protobuf:"bytes,3,opt,name=input" json:"input,omitempty"`
}

func (m *RequestContext) Reset()                    { *m = RequestContext{} }
func (m *RequestContext) String() string            { return proto.CompactTextString(m) }
func (*RequestContext) ProtoMessage()               {}
func (*RequestContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestContext) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *RequestContext) GetSevice() string {
	if m != nil {
		return m.Sevice
	}
	return ""
}

func (m *RequestContext) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type ResponseContext struct {
	Status int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *ResponseContext) Reset()                    { *m = ResponseContext{} }
func (m *ResponseContext) String() string            { return proto.CompactTextString(m) }
func (*ResponseContext) ProtoMessage()               {}
func (*ResponseContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseContext) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponseContext) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type HBRequest struct {
	Ping int32 `protobuf:"varint,1,opt,name=Ping" json:"Ping,omitempty"`
}

func (m *HBRequest) Reset()                    { *m = HBRequest{} }
func (m *HBRequest) String() string            { return proto.CompactTextString(m) }
func (*HBRequest) ProtoMessage()               {}
func (*HBRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HBRequest) GetPing() int32 {
	if m != nil {
		return m.Ping
	}
	return 0
}

type HBResponse struct {
	Pong int32 `protobuf:"varint,2,opt,name=Pong" json:"Pong,omitempty"`
}

func (m *HBResponse) Reset()                    { *m = HBResponse{} }
func (m *HBResponse) String() string            { return proto.CompactTextString(m) }
func (*HBResponse) ProtoMessage()               {}
func (*HBResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HBResponse) GetPong() int32 {
	if m != nil {
		return m.Pong
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestContext)(nil), "grpc4ars.RequestContext")
	proto.RegisterType((*ResponseContext)(nil), "grpc4ars.ResponseContext")
	proto.RegisterType((*HBRequest)(nil), "grpc4ars.HBRequest")
	proto.RegisterType((*HBResponse)(nil), "grpc4ars.HBResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ARS service

type ARSClient interface {
	Request(ctx context.Context, in *RequestContext, opts ...grpc.CallOption) (*ResponseContext, error)
	Heartbeat(ctx context.Context, in *HBRequest, opts ...grpc.CallOption) (*HBResponse, error)
}

type aRSClient struct {
	cc *grpc.ClientConn
}

func NewARSClient(cc *grpc.ClientConn) ARSClient {
	return &aRSClient{cc}
}

func (c *aRSClient) Request(ctx context.Context, in *RequestContext, opts ...grpc.CallOption) (*ResponseContext, error) {
	out := new(ResponseContext)
	err := grpc.Invoke(ctx, "/grpc4ars.ARS/Request", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aRSClient) Heartbeat(ctx context.Context, in *HBRequest, opts ...grpc.CallOption) (*HBResponse, error) {
	out := new(HBResponse)
	err := grpc.Invoke(ctx, "/grpc4ars.ARS/Heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ARS service

type ARSServer interface {
	Request(context.Context, *RequestContext) (*ResponseContext, error)
	Heartbeat(context.Context, *HBRequest) (*HBResponse, error)
}

func RegisterARSServer(s *grpc.Server, srv ARSServer) {
	s.RegisterService(&_ARS_serviceDesc, srv)
}

func _ARS_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ARSServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc4ars.ARS/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ARSServer).Request(ctx, req.(*RequestContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _ARS_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ARSServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc4ars.ARS/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ARSServer).Heartbeat(ctx, req.(*HBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ARS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc4ars.ARS",
	HandlerType: (*ARSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _ARS_Request_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ARS_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x1b, 0x4a, 0x5b, 0x72, 0x03, 0x48, 0x47, 0x85, 0x4c, 0x17, 0x2a, 0x4f, 0x4c, 0x19,
	0x80, 0x81, 0x91, 0xc2, 0xd2, 0x11, 0x99, 0x85, 0x35, 0x8d, 0x4e, 0x51, 0x24, 0x64, 0x1b, 0xdf,
	0x05, 0xb1, 0xf2, 0xcf, 0x51, 0x1c, 0x1b, 0x9a, 0xcd, 0xef, 0xdd, 0xf3, 0xe7, 0x77, 0x86, 0x32,
	0xf8, 0xa6, 0xf2, 0xc1, 0x89, 0xc3, 0xb3, 0x36, 0xf8, 0xe6, 0xa1, 0x0e, 0xac, 0xdf, 0xe1, 0xdc,
	0xd0, 0x67, 0x4f, 0x2c, 0x2f, 0xce, 0x0a, 0x7d, 0x0b, 0x2a, 0x58, 0x31, 0x31, 0x77, 0xce, 0xaa,
	0x62, 0x5b, 0xdc, 0x96, 0x26, 0x4b, 0xbc, 0x82, 0x25, 0xd3, 0x57, 0xd7, 0x90, 0x3a, 0x89, 0x83,
	0xa4, 0x70, 0x0d, 0x8b, 0xce, 0xfa, 0x5e, 0xd4, 0x3c, 0xda, 0xa3, 0xd0, 0x3b, 0xb8, 0x30, 0xc4,
	0xde, 0x59, 0xa6, 0x8c, 0x1e, 0x00, 0x52, 0x4b, 0xcf, 0x91, 0xbc, 0x30, 0x49, 0x0d, 0x7e, 0x20,
	0xee, 0x3f, 0x24, 0x83, 0x47, 0xa5, 0x6f, 0xa0, 0xdc, 0x3f, 0xa7, 0x7a, 0x88, 0x70, 0xfa, 0xda,
	0xd9, 0x36, 0x5d, 0x8d, 0x67, 0xbd, 0x05, 0x18, 0x02, 0xe3, 0x2b, 0x31, 0xe1, 0x6c, 0x1b, 0x21,
	0x43, 0xc2, 0xd9, 0xf6, 0xee, 0xa7, 0x80, 0xf9, 0xce, 0xbc, 0xe1, 0x13, 0xac, 0x32, 0x48, 0x55,
	0x79, 0xfb, 0x6a, 0xba, 0xfa, 0xe6, 0xfa, 0x78, 0x32, 0xa9, 0xae, 0x67, 0xf8, 0x08, 0xe5, 0x9e,
	0xea, 0x20, 0x07, 0xaa, 0x05, 0x2f, 0xff, 0x93, 0x7f, 0x0d, 0x37, 0xeb, 0xa9, 0x39, 0x02, 0xf4,
	0xec, 0xb0, 0x8c, 0x9f, 0x7e, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x3f, 0xf7, 0x19, 0x81,
	0x01, 0x00, 0x00,
}
